<h3>BONJOUR,</h3>

<p>
NOUS AVONS BIEN REÇU VOTRE DEMANDE ET NOUS VOUS EN REMERCIONS.
</p>
<p>
NOUS VOUS CONTACTERONS DANS LES 24 HEURES QUI SUIVENT POUR VOUS CONFIRMER VOTRE RÉSERVATION.

</p>

<h4>CORDIALEMENT,</h4>

<h5>LocVoi</h5>